# Labolatorium 3 - NumPy
**Ania**

Ćwizcenie 1

In [4]:
import numpy as np

In [2]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
dziesiatki = np.arange(0,101,10)
print(f"Dziesiatki: {dziesiatki}")

Dziesiatki: [  0  10  20  30  40  50  60  70  80  90 100]


In [7]:
ulamki = np.linspace(0,1,7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
np.random.seed(42)
losowe_oceny = np.random.randint(2,6,size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int64


Ćwizcenie 2

In [10]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

In [12]:
# Sprzedaz w styczniu
print(f"Sprzedaz w styczniu: {miesiace_sprzedaz[0]}")

Sprzedaz w styczniu: 120


In [13]:
# Sprzedaz w grudniu
print(f"Sprzedaz w grudniu: {miesiace_sprzedaz[-1]}")

Sprzedaz w grudniu: 221


In [14]:
# Sprzedaz w Q1
print(f"Sprzedaz w Q1: {miesiace_sprzedaz[0:3]}")

Sprzedaz w Q1: [120 135  98]


In [15]:
# Sprzedaz w Q4
print(f"Sprzedaz w Q4: {miesiace_sprzedaz[-3:]}")

Sprzedaz w Q4: [143 198 221]


In [17]:
# Sprzedaz co drugi miesiac
print(f"Sprzedaz co drugi miesiac: {miesiace_sprzedaz[::2]}")

Sprzedaz co drugi miesiac: [120  98 167 201 156 198]


In [18]:
# Sprzedaz od tylu
print(f"Sprzedaz od tylu: {miesiace_sprzedaz[::-1]}")

Sprzedaz od tylu: [221 198 143 156 178 201 189 167 142  98 135 120]


In [19]:
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [22]:
# Sprzedaz produktu A w Q2
print(f"{produkty[0]} w {kwartaly[1]} = {dane[0,1]}")

Produkt A w Q2 = 145


In [23]:
# Cala sprzedaz produktu C 
print(f"Cala sprzedaz {produkty[2]}: {dane[2]}")

Cala sprzedaz Produkt C: [234 267 289]


In [24]:
# Sprzedaz wszystkich produktow w Q1
print(f"Sprzedaz wszystkich produktow w Q1: {dane[:,0]}")

Sprzedaz wszystkich produktow w Q1: [120  89 234  56]


In [29]:
# Sprzedaz produktow B i C w Q2 i Q3
print(f"Sprzedaz {produkty[1]} i {produkty[2]} w {kwartaly[1]} wyniosla: {dane[1:3, 1:]}")

Sprzedaz Produkt B i Produkt C w Q2 wyniosla: [[102  95]
 [267 289]]


Ćwiczenie 3

In [5]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [6]:
srednia = ceny.mean()
max_cena = ceny.max()
min_cena = ceny.min()

najdrozszy = nazwy[ceny.argmax()]
najtanszy = nazwy[ceny.argmin()]

print(srednia)
print(najdrozszy, max_cena)
print(najtanszy, min_cena)

1171.0
Laptop 3499
Ładowarka 89


In [7]:
wartosci = ceny * ilosci_magazyn
laczna_wartosc = wartosci.sum()

print(wartosci)
print(laczna_wartosc)

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
549465


In [8]:
rabat = ceny * 0.85
vat = ceny * 1.23

ile_pow_1000 = (ceny > 1000).sum()

print(rabat)
print(vat)
print(ile_pow_1000)

[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
4


In [9]:
nazwy = np.array(nazwy)

maska_oceny = oceny_klientow >= 4.5
print(nazwy[maska_oceny])
print(ceny[maska_oceny])

maska_tanie = ceny < 200
print(nazwy[maska_tanie])
print(ilosci_magazyn[maska_tanie])

['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
[3499 2499  349 1499]
['Ładowarka' 'Mysz']
[312 201]


In [10]:
maska_niskie = ilosci_magazyn < 30

print(nazwy[maska_niskie])

wartosci = ceny * ilosci_magazyn
wartosc_niskie = wartosci[maska_niskie].sum()

procent = (wartosc_niskie / wartosci.sum()) * 100

print(wartosc_niskie)
print(procent)

['Laptop' 'Monitor']
86962
15.826667758637946


In [11]:
okazje = (oceny_klientow >= 4.5) & (ceny < 1000)

print(nazwy[okazje])
print(ceny[okazje])

srednia_wysokie = ceny[oceny_klientow >= 4.0].mean()
srednia_niskie = ceny[oceny_klientow < 4.0].mean()

print(srednia_wysokie)
print(srednia_niskie)

['Słuchawki']
[349]
1446.142857142857
529.0


Ćwiczenie 4

In [12]:
import time

In [13]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [14]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 35.1 ms
NumPy: 1.9 ms
NumPy jest 19× szybszy!


In [15]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 8.1 ms
NumPy: 0.5 ms
NumPy jest 16× szybszy!


In [16]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 27.0 ms
NumPy: 1.2 ms
NumPy jest 23× szybszy!


## Wnioski z benchmarku
- NumPy jest **19x** szybszy w mnożeniu
- NumPy jest **16x** szybszy w sumowaniu
- NumPy jest **23x** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list